HotelSolution/src/main/java/com/hotelsolution/fire/front/controller/FrontController.java, HotelSolution/src/main/webapp/WEB-INF/views/front/roomStatus/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/front/roomStatus/list.jsp, HotelSolution/src/main/webapp/WEB-INF/views/front/useBook/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/front/useBook/list.jsp, HotelSolution/src/main/webapp/WEB-INF/views/front/useManage/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/front/useManage/list.jsp
=> 객실이용 ui화면 구현

HotelSolution/src/main/webapp/WEB-INF/views/common/home.jsp, HotelSolution/src/main/webapp/resources/css/common/aside.css, HotelSolution/src/main/webapp/resources/css/common/header.css, HotelSolution/src/main/webapp/resources/css/common/home.css
=> 헤더 푸터 메인 css수정함

HotelSolution/src/main/java/com/hotelsolution/fire/hr/controller/SurveyController.java, HotelSolution/src/main/java/com/hotelsolution/fire/hr/dao/SurveyDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/hr/service/SurveyService.java, HotelSolution/src/main/resources/mybatis/mapper/survey-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/hr/survey/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/hr/survey/list.jsp, HotelSolution/src/main/webapp/WEB-INF/views/hr/survey/write.jsp
=> 설문지 화면이 너무 90년대다

HotelSolution/src/main/java/com/hotelsolution/fire/common/page/vo/PageVo.java, HotelSolution/src/main/java/com/hotelsolution/fire/temp/FireConstPool.java
상수정의하는 폴더추가 ,common에 페이징용 pagevo 올림
=> 상수정의하는 폴더추가 ,common에 페이징용 pagevo 올림

HotelSolution/src/main/java/com/hotelsolution/fire/front/controller/FrontController.java, HotelSolution/src/main/java/com/hotelsolution/fire/restaurant/controller/RestaurantController.java, HotelSolution/src/main/webapp/WEB-INF/views/front/articleManage.jsp, HotelSolution/src/main/webapp/WEB-INF/views/restaurant/articleManage.jsp, HotelSolution/src/main/webapp/WEB-INF/views/restaurant/menuManage.jsp, HotelSolution/src/main/webapp/WEB-INF/views/restaurant/roomOrder.jsp
=> 식당 물품재고관리 , 메뉴관리

HotelSolution/src/main/java/com/hotelsolution/fire/board/controller/CompanyBoardController.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/dao/CompanyBoardDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/dao/CompanyBoardDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardService.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardServiceImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/vo/CompanyBoardVo.java, HotelSolution/src/main/resources/mybatis/conf.xml, HotelSolution/src/main/resources/mybatis/mapper/companyboard-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/common/aside.jsp, HotelSolution/src/main/webapp/WEB-INF/views/front/companyBoard/list.jsp, HotelSolution/src/main/webapp/resources/css/companyboard/list.css
사내게시판 목록 조회하기 페이지 만듬 con에 타입등록함 사이드 글자 수정함
=> 사내게시판 목록 조회하기 페이지 만듬 con에 타입등록함 사이드 글자 수정함

HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/controller/DataRoomController.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/dao/DataRoomDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/dao/DataRoomDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/service/DataRoomService.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/service/DataRoomServiceImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/vo/DataRoomFileVo.java, HotelSolution/src/main/java/com/hotelsolution/fire/hr/controller/SurveyController.java, HotelSolution/src/main/resources/mybatis/conf.xml, HotelSolution/src/main/resources/mybatis/mapper/dataroom-mapper.xml, HotelSolution/src/main/resources/mybatis/mapper/survey-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/dataroom/list.jsp, HotelSolution/src/main/webapp/WEB-INF/views/dataroom/write.jsp, HotelSolution/src/main/webapp/WEB-INF/views/hr/survey/answer-list.jsp, HotelSolution/src/main/webapp/WEB-INF/views/hr/survey/create.jsp, HotelSolution/src/main/webapp/WEB-INF/views/hr/survey/detail-list.jsp, HotelSolution/src/main/webapp/WEB-INF/views/hr/survey/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/hr/survey/write.jsp
=> 자료실 작성 완료 리스트 진행중

HotelSolution/src/main/webapp/WEB-INF/views/common/header.jsp, HotelSolution/src/main/webapp/resources/css/common/aside.css, HotelSolution/src/main/webapp/resources/css/common/header.css
=> 헤더 어사이드 크기 수정함

HotelSolution/src/main/java/com/hotelsolution/fire/board/controller/CompanyBoardController.java, HotelSolution/src/main/webapp/WEB-INF/views/common/home.jsp, HotelSolution/src/main/webapp/WEB-INF/views/common/mainaside.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/write.jsp, HotelSolution/src/main/webapp/resources/css/common/mainaside.css, HotelSolution/src/main/webapp/resources/css/companyboard/detail.css
=> 메인안에 사이드바 인클루드로 분리함

HotelSolution/src/main/webapp/WEB-INF/views/common/mainaside.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/detail.jsp, HotelSolution/src/main/webapp/resources/css/common/header.css, HotelSolution/src/main/webapp/resources/css/common/home.css, HotelSolution/src/main/webapp/resources/css/common/mainaside.css, HotelSolution/src/main/webapp/resources/css/companyboard/detail.css
=> 홈화면 css 수정및 내용 추가함

HotelSolution/src/main/java/com/hotelsolution/fire/mail/controller/MailController.java, HotelSolution/src/main/java/com/hotelsolution/fire/mail/service/MailService.java, HotelSolution/src/main/java/com/hotelsolution/fire/mail/vo/MailAttachmentVo.java, HotelSolution/src/main/java/com/hotelsolution/fire/mail/vo/MailVo.java, HotelSolution/src/main/webapp/WEB-INF/views/common/mainaside.jsp, HotelSolution/src/main/webapp/WEB-INF/views/mail/list.jsp, HotelSolution/src/main/webapp/WEB-INF/views/mail/post.jsp, HotelSolution/src/main/webapp/resources/css/companyboard/detail.css, HotelSolution/src/main/webapp/resources/css/mail/detail.css, HotelSolution/src/main/webapp/resources/css/mail/list.css, HotelSolution/src/main/webapp/resources/css/mail/post.css, HotelSolution/src/main/webapp/resources/js/mail/list.js
=> 메일 쓰기 페이지 css html추가함

HotelSolution/src/main/java/com/hotelsolution/fire/mail/controller/MailController.java, HotelSolution/src/main/webapp/WEB-INF/views/mail/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/mail/mailSuccess.jsp, HotelSolution/src/main/webapp/resources/css/mail/detail.css, HotelSolution/src/main/webapp/resources/css/mail/success.css
=> 메일상세보기작업함 ㅇㅇ

HotelSolution/src/main/webapp/WEB-INF/views/common/main.jsp, HotelSolution/src/main/webapp/WEB-INF/views/front/bookManage/detail.jsp
=> 홈화면 수정 final

HotelSolution/src/main/java/com/hotelsolution/fire/member/controller/MemberController.java, HotelSolution/src/main/java/com/hotelsolution/fire/member/dao/MemberDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/member/dao/MemberDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/member/service/MemberService.java, HotelSolution/src/main/java/com/hotelsolution/fire/member/service/MemberServiceImpl.java, HotelSolution/src/main/resources/mybatis/mapper/member-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/member/join.jsp
=> 회원가입 파일빼고 완료

HotelSolution/src/main/java/com/hotelsolution/fire/mail/controller/MailController.java, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/list.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/write.jsp, HotelSolution/src/main/webapp/WEB-INF/views/mail/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/mail/list.jsp, HotelSolution/src/main/webapp/WEB-INF/views/mail/mailSuccess.jsp, HotelSolution/src/main/webapp/WEB-INF/views/mail/post.jsp, HotelSolution/src/main/webapp/resources/css/companyboard/write.css
=> 전부 div mainboard로 바꿈

HotelSolution/src/main/java/com/hotelsolution/fire/board/controller/CompanyBoardController.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/dao/CompanyBoardDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardService.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardServiceImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/vo/CompanyBoardCategoryVo.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/vo/CompanyBoardVo.java, HotelSolution/src/main/resources/mybatis/mapper/companyboard-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/list.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/write.jsp, HotelSolution/src/main/webapp/WEB-INF/views/mail/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/mail/list.jsp, HotelSolution/src/main/webapp/resources/css/companyboard/list.css, HotelSolution/src/main/webapp/resources/css/companyboard/write.css, HotelSolution/src/main/webapp/resources/js/companyboard/list.js
=> 게시글 글쓰기 완료

HotelSolution/pom.xml, HotelSolution/src/main/java/com/hotelsolution/fire/mail/send/MailSendService.java, HotelSolution/src/main/java/com/hotelsolution/fire/member/controller/MemberController.java, HotelSolution/src/main/java/com/hotelsolution/fire/member/dao/MemberDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/member/dao/MemberDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/member/service/MemberService.java, HotelSolution/src/main/java/com/hotelsolution/fire/member/service/MemberServiceImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/member/vo/MemberVo.java, HotelSolution/src/main/resources/mybatis/mapper/member-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/spring/context-mail.xml, HotelSolution/src/main/webapp/WEB-INF/views/member/emailAuthentication.jsp, HotelSolution/src/main/webapp/WEB-INF/views/member/join.jsp, HotelSolution/src/main/webapp/WEB-INF/views/member/login.jsp
로그인 완료, 맞지 않을시 로그인 못하게
비밀번호 재설정 메일 진행중
=> 회원가입 프로필 사진 미리보기 완료

HotelSolution/src/main/java/com/hotelsolution/fire/board/controller/CompanyBoardController.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/home/controller/homeController.java, HotelSolution/src/main/java/com/hotelsolution/fire/main/controller/MainController.java, HotelSolution/src/main/webapp/WEB-INF/views/common/main.jsp, HotelSolution/src/main/webapp/resources/js/common/main-aside.js
홈컨트롤러 패키지 common/home/controller로 바꿈 메인 사이드바 c:if태그로 부서별로 메뉴 보이게수정함
=> 홈컨트롤러 패키지 common/home/controller로 바꿈 메인 사이드바 c:if태그로 부서별로 메뉴 보이게수정함

HotelSolution/src/main/webapp/WEB-INF/views/common/main.jsp
=> 사이드바 js 메일 게시판링크추가함

HotelSolution/src/main/java/com/hotelsolution/fire/common/schedule/controller/ScheduleController.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/schedule/dao/ScheduleDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/schedule/service/ScheduleService.java, HotelSolution/src/main/resources/mybatis/mapper/schedule-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/schedule/calendar.jsp, HotelSolution/src/main/webapp/WEB-INF/views/schedule/create.jsp
=> 일정 끝 풀캘린더 이용 팀일정은 같은팀 공유

HotelSolution/src/main/java/com/hotelsolution/fire/board/controller/CompanyBoardController.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/dao/CompanyBoardDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/dao/CompanyBoardDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardService.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardServiceImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/interceptor/CheckSessionInterceptor.java, HotelSolution/src/main/resources/mybatis/mapper/companyboard-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/edit.jsp
로그인 안하면 member/login으로 보내버리는 인터셉터  추가함
=> 로그인 안하면 member/login으로 보내버리는 인터셉터  추가함

HotelSolution/src/main/java/com/hotelsolution/fire/board/controller/CompanyBoardController.java, HotelSolution/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, HotelSolution/src/main/webapp/WEB-INF/views/common/main.jsp, HotelSolution/src/main/webapp/resources/js/common/main-aside.js
로그인후 화면에서도 홈컨트롤러도 로그인화면으로보내게 한줄수정, 팀메뉴바 a태그에 클래스 넣음
=> 로그인후 화면에서도 홈컨트롤러도 로그인화면으로보내게 한줄수정, 팀메뉴바 a태그에 클래스 넣음

HotelSolution/src/main/java/com/hotelsolution/fire/front/controller/FrontController.java, HotelSolution/src/main/java/com/hotelsolution/fire/front/dao/FrontDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/front/dao/FrontDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/front/service/FrontService.java, HotelSolution/src/main/java/com/hotelsolution/fire/front/service/FrontServiceImpl.java, HotelSolution/src/main/resources/mybatis/mapper/front-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/front/articleManage.jsp
=> 객실 물품 재고 관리 완료 발주할거 가기 버튼만 하면됌

HotelSolution/src/main/java/com/hotelsolution/fire/board/controller/CompanyBoardController.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/dao/CompanyBoardDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/dao/CompanyBoardDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardService.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardServiceImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/vo/CommentResponse.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/vo/CompanyBoardCommentVo.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/vo/CompanyBoardVo.java, HotelSolution/src/main/java/com/hotelsolution/fire/temp/FireConstPool.java, HotelSolution/src/main/resources/mybatis/conf.xml, HotelSolution/src/main/resources/mybatis/mapper/companyboard-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/edit.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/list.jsp, HotelSolution/src/main/webapp/resources/css/companyboard/list.css
게시판 댓글리스트 보여주기 ajax에 담기까지함 게시글 crud까지는 다 함 댓글 페이징 상수 pagevo에추가
=> 게시판 댓글리스트 보여주기 ajax에 담기까지함 게시글 crud까지는 다 함 댓글 페이징 상수 pagevo에추가

HotelSolution/src/main/java/com/hotelsolution/fire/board/controller/CompanyBoardController.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/dao/CompanyBoardDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/dao/CompanyBoardDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardService.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardServiceImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/vo/CommentResponse.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/vo/CompanyBoardCommentVo.java, HotelSolution/src/main/resources/mybatis/mapper/companyboard-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/detail.jsp, HotelSolution/src/main/webapp/resources/css/companyboard/detail.css
=> 게시판 원 댓글리스트 페이징해서 보여주기 추가함

HotelSolution/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
로그인전 이메일인증 인터셉터 exclude경로 하나 추가함
=> 로그인전 이메일인증 인터셉터 exclude경로 하나 추가함

HotelSolution/src/main/java/com/hotelsolution/fire/board/controller/CompanyBoardController.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/dao/CompanyBoardDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/dao/CompanyBoardDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardService.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardServiceImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/vo/CompanyBoardVo.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/home/controller/homeController.java, HotelSolution/src/main/resources/mybatis/mapper/companyboard-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/common/main.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/list.jsp, HotelSolution/src/main/webapp/resources/css/companyboard/list.css, HotelSolution/src/main/webapp/resources/js/common/main-aside.js
게시판 댓글 조회수 가져오는 쿼리문 추가 메인.jsp에 css수정함
=> 게시판 댓글 조회수 가져오는 쿼리문 추가 메인.jsp에 css수정함

HotelSolution/src/main/java/com/hotelsolution/fire/board/controller/CompanyBoardController.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/dao/CompanyBoardDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/dao/CompanyBoardDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardService.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/service/CompanyBoardServiceImpl.java, HotelSolution/src/main/resources/mybatis/mapper/companyboard-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/common/home.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/list.jsp, HotelSolution/src/main/webapp/resources/css/common/home.css
=> 게시판리스트검색처리함

HotelSolution/src/main/java/com/hotelsolution/fire/board/controller/CompanyBoardController.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/vo/CompanyBoardCommentVo.java, HotelSolution/src/main/java/com/hotelsolution/fire/board/vo/CompanyBoardVo.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/temp/FireConstPool.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/util/DateUtil.java, HotelSolution/src/main/resources/mybatis/mapper/companyboard-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/list.jsp
=> 게시판날짜형식바꾸는 클래스 추가함

HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/controller/DataRoomController.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/dao/DataRoomDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/dao/DataRoomDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/service/DataRoomServiceImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/hr/controller/EmployeeManagementController.java, HotelSolution/src/main/resources/mybatis/mapper/dataroom-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/chat/rooms.jsp, HotelSolution/src/main/webapp/WEB-INF/views/dataroom/detail.jsp, HotelSolution/src/main/webapp/WEB-INF/views/hr/em/getDetail.jsp
=> 자료실 삭제 기능 추가 , 인사팀 사운 ㅓ상세조회 근태 관리 목록 추가, div로 변경

HotelSolution/src/main/webapp/WEB-INF/views/common/home.jsp, HotelSolution/src/main/webapp/resources/css/common/home.css
=> 메인화면에서 통근관리 바로가기 추가함

HotelSolution/src/main/java/com/hotelsolution/fire/approval/controller/ApprovalController.java, HotelSolution/src/main/java/com/hotelsolution/fire/approval/dao/ApprovalDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/approval/dao/ApprovalDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/approval/service/ApprovalService.java, HotelSolution/src/main/java/com/hotelsolution/fire/approval/service/ApprovalServiceImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/approval/vo/ApprovalReferrerVo.java, HotelSolution/src/main/java/com/hotelsolution/fire/approval/vo/ApprovalVo.java, HotelSolution/src/main/java/com/hotelsolution/fire/approval/vo/ApproverVo.java, HotelSolution/src/main/resources/mybatis/mapper/approval-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/approval/approvalFirstPage.jsp, HotelSolution/src/main/webapp/WEB-INF/views/approval/expenditure.jsp, HotelSolution/src/main/webapp/WEB-INF/views/approval/getApproval.jsp, HotelSolution/src/main/webapp/WEB-INF/views/approval/referrerApproval.jsp, HotelSolution/src/main/webapp/WEB-INF/views/approval/report.jsp, HotelSolution/src/main/webapp/WEB-INF/views/approval/vaction.jsp, HotelSolution/src/main/webapp/WEB-INF/views/approval/vactionDetail.jsp
=> 내가받은결재 에서 휴가신청서 상세조회

HotelSolution/src/main/java/com/hotelsolution/fire/common/home/controller/homeController.java, HotelSolution/src/main/webapp/WEB-INF/views/common/home.jsp, HotelSolution/src/main/webapp/WEB-INF/views/common/main.jsp, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/post.jsp
=> 일정 홈화면에가져오는거 메인 진행중

HotelSolution/src/main/java/com/hotelsolution/fire/common/chat/controller/ChatRoomController.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/dao/DataRoomDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/dao/DataRoomDaoImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/service/DataRoomService.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/dataroom/service/DataRoomServiceImpl.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/home/controller/homeController.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/schedule/controller/ScheduleController.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/schedule/dao/ScheduleDao.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/schedule/service/ScheduleService.java, HotelSolution/src/main/java/com/hotelsolution/fire/common/schedule/vo/ScheduleVo.java, HotelSolution/src/main/resources/mybatis/mapper/schedule-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, HotelSolution/src/main/webapp/WEB-INF/views/chat/room.jsp, HotelSolution/src/main/webapp/WEB-INF/views/common/home.jsp, HotelSolution/src/main/webapp/WEB-INF/views/common/main.jsp, HotelSolution/src/main/webapp/WEB-INF/views/dataroom/list.jsp, HotelSolution/src/main/webapp/WEB-INF/views/hr/vacation/vaclist.jsp, HotelSolution/src/main/webapp/resources/css/common/home.css
=> 홈,메인 많이 수정함 // 에러시 전화 주세요

HotelSolution/src/main/java/com/hotelsolution/fire/board/controller/CompanyBoardController.java, HotelSolution/src/main/resources/mybatis/mapper/companyboard-mapper.xml, HotelSolution/src/main/webapp/WEB-INF/views/companyBoard/detail.jsp
=> 게시판리스트 쿼리부분 수정함

HotelSolution/src/main/webapp/WEB-INF/views/common/home.jsp, HotelSolution/src/main/webapp/WEB-INF/views/schedule/calendar.jsp
=> 다시 또 건들면 내가 사람이 아니다
